const VALIDATION_ERROR_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const DEFAULT_ERROR_STATUS_CODE = 500;
const CONFLICT_ERROR_STATUS_CODE = 409;
const UNAUTHORIZED_ERROR_STATUS_CODE = 401;
const FORBIDDEN_ERROR_STATUS_CODE = 403;

module.exports = { VALIDATION_ERROR_STATUS_CODE, NOT_FOUND_STATUS_CODE, DEFAULT_ERROR_STATUS_CODE, CONFLICT_ERROR_STATUS_CODE, UNAUTHORIZED_ERROR_STATUS_CODE, FORBIDDEN_ERROR_STATUS_CODE };